name: Create Build

on:
  push:
    branches:
      - master

jobs:
  # Windows
  build_windows:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build app for release
      run: msbuild App2-uwp-dx11.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: display
      shell: bash
      run: |
        ls -R
