name: Create Build

on:
  push:
    branches:
      - master

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path ./ -ChildPath App2_uwp_dx11_TemporaryKey.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
    - name: checkout
      uses: actions/checkout@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build app for release
      run: msbuild App2-uwp-dx11.vcxproj /p:AppxBundlePlatforms="$env:Appx_Bundle_Platforms" /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=App2_uwp_dx11_TemporaryKey.pfx /p:AppxPackageDir="$env:Appx_Package_Dir" /p:GenerateAppxPackageOnBuild=true
      env:
        Appx_Bundle: Never
        Appx_Bundle_Platforms: x64
        Appx_Package_Build_Mode: SideloadOnly
        Appx_Package_Dir: Packages\
        Configuration: Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MSIX Package
        path: Packages/**/App2-uwp-dx11*.msix
    # Create the unpackaged app
    - name: Build unpackaged app
      run: msbuild App2-uwp-dx11.vcxproj /t:Publish /p:WindowsPackageType=None /p:Configuration=Release /p:Platform=x64
      env:
        Configuration: Release
    - name: Create ZIP of unpackaged app
      run: Compress-Archive bin/x64/Release/net5.0-windows10.0.19041.0/publish/* 'App2-uwp-dx11-unpackaged-0.${{ github.run_number }}.${{ github.run_attempt }}.0.zip'
    - name: Upload unpackaged app
      uses: actions/upload-artifact@v2
      with:
        name: 'Unpackaged app'
        path: 'App2-uwp-dx11-unpackaged-0.${{ github.run_number }}.${{ github.run_attempt }}.0.zip'
    - name: display
      shell: bash
      run: |
        ls -R

#run: msbuild App2-uwp-dx11.vcxproj -property:Configuration=Release;AppxBundle=Always;AppxBundlePlatforms="x86|x64|ARM" /p:BuildAppxUploadPackageForUap=true
#run: msbuild App2-uwp-dx11.vcxproj -property:Configuration=Release
#$certificatePath = Join-Path -Path App2_uwp_dx11 -ChildPath App2_uwp_dx11_TemporaryKey.pfx
